import type { Dictionary, TableRow } from "./fr";

export const en: Dictionary = {
  meta: {
    title: "Remakeit — Create viral videos that pay, automatically.",
    description:
      "Paste a YouTube URL or write a prompt. Remakeit generates a viral video ready to post.",
    pricingTitle: "Pricing — Remakeit",
  },
  nav: {
    howItWorks: "How it works",
    features: "Features",
    results: "Results",
    pricing: "Pricing",
    faq: "FAQ",
    login: "Log in",
    signup: "Sign up",
  },
  hero: {
    badge: "#1 AI TOOL",
    users: "+50k active users",
    titleLine1: "Create",
    titleHighlight: "viral videos",
    titleLine2: "that pay, automatically.",
    subtitle:
      "Paste a YouTube URL or write a prompt. Remakeit generates a viral video ready to post.",
    cta: "Try it",
    pills: ["100% automatic", "TikTok optimized", "Ready to post"],
  },
  socialProof: {
    highlight: "1M+ creators",
    title: "generate billions of views with Remakeit",
    subtitle:
      "Every day thousands of creators use Remakeit to generate viral shorts. Join them.",
    cards: [
      { title: "Views = Money", text: "+1000 monetized viral videos every day." },
      { title: "Automations", text: "Schedule, publish, then broadcast to your networks in one click." },
      { title: "All in one", text: "All your video tools, gathered in a single place." },
    ],
  },
  clipping: {
    badge: "Clipping",
    titleLine1: "Turn any video into multiple",
    titleHighlight: "viral clips in under 5 min",
    subtitle: "Posted straight to your social networks",
    tryIt: "See for yourself",
    cta: "Try it",
  },
  aiGeneration: {
    badge: "AI Generation",
    titleLine1: "Or generate",
    titleHighlight: "viral AI videos",
    titleLine2: "With the best models available today",
    modelName: "Veo 3",
    modelText: "Create AI videos in seconds from a simple prompt",
    generate: "Generate",
    footnote: "Try our generation models for free",
  },
  bestSoftware: {
    badge: "The best software on the market",
    titleLine1: "The only tool",
    titleHighlight: "you will ever need.",
  },
  howItWorks: {
    badge: "How it works",
    titleLine1: "From idea to viral video",
    titleHighlight: "in 3 clicks",
    subtitle: "No editing. No skills. Just viral content ready to explode",
    steps: [
      {
        n: "1",
        title: "Paste a YouTube URL",
        text: 'Want to start from scratch? Write a prompt (e.g. "Top 5 Messi goals.")',
        placeholder: "Enter a URL / prompt...",
        action: "generate",
      },
      {
        n: "2",
        title: "AI does the editing",
        text: "Best moments cut, dynamic captions, vertical reframing. In 30 seconds.",
        placeholder: "Analyzing highlights...",
        action: "edit",
      },
      {
        n: "3",
        title: "Publish everywhere in one click",
        text: "TikTok, Reels, Shorts. Schedule your posts and let the algorithm work.",
        placeholder: "Schedule publication...",
        action: "publish",
      },
    ],
    next: "Next step",
  },
  features: {
    badge: "Features",
    title: "Everything you need",
    subtitle:
      "Recycle your YouTube videos, create viral content from scratch, and publish everywhere automatically. Without ever leaving Remakeit",
    cta: "Try it",
    tabs: [
      {
        label: "Clipping",
        titleLine1: "Recycle your YouTube",
        titleHighlight: "videos into viral shorts",
        text: "Paste a YouTube URL. Remakeit cuts the best moments, adds captions, optimizes for TikTok/Reels/Shorts. In 30 seconds",
      },
      {
        label: "AI Generation",
        titleLine1: "Create videos",
        titleHighlight: "fully generated by AI",
        text: "A simple prompt is enough. Remakeit uses the best models on the market to produce 16:9 or 9:16 videos, ready to post.",
      },
      {
        label: "Auto-publish",
        titleLine1: "Schedule and publish",
        titleHighlight: "across all your networks",
        text: "Connect your TikTok, Instagram and YouTube accounts. Remakeit posts at the best time with optimized hashtags and description.",
      },
      {
        label: "Tools",
        titleLine1: "Captions, voiceovers,",
        titleHighlight: "music and analytics",
        text: "Realistic voiceovers, designed captions, smart YouTube search and a performance dashboard. All in the same place.",
      },
    ],
  },
  comparison: {
    us: "Remakeit",
    them: "With other tools",
    rows: [
      { us: "AI creates your video", them: "Manual cutting" },
      { us: "Scheduling & direct publishing", them: "No multi-network publishing" },
      { us: "Format optimization", them: "Several tools required" },
      { us: "Simple and fast interface", them: "Less effective results" },
    ],
  },
  why: {
    titleLine1: "Why Remakeit is the",
    titleHighlight: "best tool",
    titleLine2: "to create viral shorts",
    subtitle: "One last question before you start? Find your answer here.",
    contact: "Contact us",
    items: [
      { n: "01", title: "Time saved", text: "Video created in 30 seconds" },
      { n: "02", title: "The power of AI", text: "Full video/text/editing generation" },
      { n: "03", title: "Algorithm performance", text: "Generates views / money" },
    ],
  },
  testimonials: {
    badge: "Results",
    titleLine1: "They generate",
    titleHighlight: "millions of views",
    subtitle:
      "Creators like you have transformed their social media presence. Your turn!",
    items: [
      {
        text: "Beautiful site, works really well, I managed to generate a lot of views and revenue thanks to Remakeit",
        name: "Lucas M.",
        date: "01/12/2026",
      },
      {
        text: "Incredible tool! I multiplied my views by 10 in one week. The YouTube to TikTok conversion is perfect.",
        name: "Sarah K.",
        date: "01/28/2026",
      },
      {
        text: "I recommend it 100%. The automation saves me hours every day. My shorts are crushing it!",
        name: "Antoine D.",
        date: "02/03/2026",
      },
      {
        text: "I was skeptical at first, but the results speak for themselves. 50k views on my first generated short. The AI really picks the best moments.",
        name: "Mehdi B.",
        date: "01/22/2026",
      },
      {
        text: "Multi-network publishing changed my life. One click and my videos are on TikTok, Reels and Shorts at the same time. Huge time saver!",
        name: "Chloé R.",
        date: "02/01/2026",
      },
      {
        text: "Great tool to repurpose long content. The cutting quality is impressive and the transitions are always smooth.",
        name: "Thomas G.",
        date: "02/05/2026",
      },
    ],
    stats: [
      { value: "600+", label: "Videos /day" },
      { value: "25B+", label: "Views generated" },
      { value: "1M+", label: "Users" },
    ],
  },
  cta: {
    badge: "Join +1M creators",
    title: "Ready to generate your first millions of views?",
    button: "Create my first viral video (free)",
    trust: ["No credit card required", "Video generated in 30s", "Cancel anytime"],
  },
  faq: {
    badge: "FAQ",
    title: "Your frequently asked questions",
    subtitle: "One last question before you start? Find your answer here.",
    contact: "Contact us",
    items: [
      {
        q: "What is Remakeit?",
        a: "Remakeit is an artificial intelligence that quickly turns YouTube videos into viral, monetizable TikTok content, without requiring any editing skills.",
      },
      {
        q: "Do I need video editing skills?",
        a: "No, no editing skill is required. Remakeit simplifies the process by automating the conversion of YouTube videos into TikTok-ready formats, along with other out-of-the-box features.",
      },
      {
        q: "What are the benefits of Remakeit?",
        a: "Remakeit offers instant YouTube to TikTok conversion, drives better monetization through increased visibility, and requires no editing skills, making the process accessible to everyone.",
      },
      {
        q: "Can I monetize my videos?",
        a: "Yes, videos generated with Remakeit are designed to increase your visibility and your monetization opportunities on TikTok and other short-form platforms.",
      },
      {
        q: "Can I customize my videos after conversion?",
        a: "Yes, after automatic generation you can easily customize your videos by adding text, hashtags or other elements to boost their appeal on TikTok.",
      },
    ],
  },
  pricing: {
    badge: "Pricing",
    titleLine1: "Choose your plan.",
    titleHighlight: "Start for free.",
    subtitle: "No credit card required. Cancel anytime.",
    monthly: "Monthly",
    yearly: "Yearly",
    save: "Save",
    savePercent: "30%",
    perMonth: "/mo",
    choose: "Choose plan",
    popular: "Popular",
    footnote: "*10 credits = one video",
    plans: [
      {
        name: "Creator",
        tagline: "Ideal to get started quickly!",
        price: 22,
        features: [
          "300 credits for Remakeit Shorts*",
          "60 text-to-speech",
          "+3 background tracks",
          "Prompt to viral video",
          "Private support access",
          "Automatic publishing ⚡️",
        ],
      },
      {
        name: "Expert",
        tagline: "Unlock more features and optimize your process.",
        price: 39,
        features: [
          "600 credits for Remakeit Shorts*",
          "120 text-to-speech",
          "All background tracks",
          "Prompt to viral video",
          "Private support access",
          "Automatic publishing ⚡️",
        ],
      },
      {
        name: "Professional",
        tagline: "For professionals with several TikTok accounts",
        price: 89,
        features: [
          "Unlimited Remakeit Shorts credits",
          "Unlimited text-to-speech",
          "All background tracks",
          "Prompt to viral video",
          "Private support access",
          "Automatic publishing ⚡️",
        ],
      },
    ],
    tables: [
      {
        title: "Remakeit technology",
        header: "Features",
        rows: [
          { label: "Credits", values: ["300", "600", "Unlimited credits"] },
          { label: "YouTube video analysis", values: [true, true, true] },
          { label: "Monetizable shorts creation", values: [true, true, true] },
          { label: "Prompt to video", values: [true, true, true] },
          { label: "Remakeit x Veo3", values: [false, true, true] },
          { label: "Automatic publishing (TikTok-YouTube-Instagram) ⚡", values: [true, true, true] },
          { label: "Automatically optimized hashtags and description ⚡", values: [false, true, true] },
          { label: "Performance analytics dashboard ⚡️", values: [false, false, true] },
        ] as TableRow[],
      },
      {
        title: "Remakeit tools",
        header: "Features",
        rows: [
          { label: "Smart YouTube search", values: [true, true, true] },
          { label: "Designed captions", values: [true, true, true] },
          { label: "Realistic voiceovers", values: [true, true, true] },
          { label: "Custom voiceover intonations", values: [false, true, true] },
          { label: "Auto cuts / frame optimization", values: [true, true, true] },
          { label: "Library tutorials", values: [false, true, true] },
          { label: "Private support", values: [true, true, true] },
        ] as TableRow[],
      },
    ],
  },
  footer: {
    blurb:
      "Here are the answers to the most frequently asked questions about Remakeit. If you have more, our team is available to help you.",
    columns: [
      {
        title: "Help",
        links: [
          { label: "Community", href: "#" },
          { label: "Contact us", href: "#" },
        ],
      },
      {
        title: "Company",
        links: [
          { label: "Business proposals", href: "#" },
          { label: "Affiliation", href: "#" },
          { label: "About", href: "#" },
          { label: "Pricing", href: "/pricing" },
        ],
      },
      {
        title: "Legal",
        links: [
          { label: "Terms and conditions", href: "#" },
          { label: "Delivery policy", href: "#" },
          { label: "Legal attestation", href: "#" },
          { label: "Privacy policy", href: "#" },
          { label: "Refund policy", href: "#" },
          { label: "Cancellation policy", href: "#" },
        ],
      },
    ],
    copyright: "©2026 Remakeit",
  },
};
